### ISSUE TITLE
I18nData::NoTranslationAvailable -- countries-CURRENCY_RUB

### ISSUE THREAD

**Issue by connecticus** [pronix/spree-multi-currency#42]
If I create or edit a product - is error occurs: 

  Spree::Currency Load (0.7ms)  SELECT `spree_currencies`.\* FROM `spree_currencies` WHERE (locale like '%ru%') ORDER BY spree_currencies.locale LIMIT 1
  Spree::Price Load (0.6ms)  SELECT `spree_prices`.\* FROM `spree_prices` WHERE `spree_prices`.`deleted_at` IS NULL AND `spree_prices`.`variant_id` = 552 AND `spree_prices`.`currency` = 'RUB' ORDER BY `spree_prices`.`id` ASC LIMIT 1
  Rendered /home/stas/.rvm/gems/ruby-2.0.0-p481@nemdom/bundler/gems/spree-4f357ebbaf04/backend/app/views/spree/admin/products/_form.html.erb (63.0ms)
  Rendered /home/stas/.rvm/gems/ruby-2.0.0-p481@nemdom/bundler/gems/spree-4f357ebbaf04/backend/app/views/spree/admin/products/edit.html.erb within spree/layouts/admin (3541.3ms)
Completed 500 Internal Server Error in 3799ms

I18nData::NoTranslationAvailable (I18nData::NoTranslationAvailable -- countries-CURRENCY_RUB):
  i18n_data (0.4.1) lib/i18n_data/file_data_provider.rb:8:in `codes'
  i18n_data (0.4.1) lib/i18n_data.rb:24:in`block in countries'
  i18n_data (0.4.1) lib/i18n_data.rb:57:in `fetch'
  i18n_data (0.4.1) lib/i18n_data.rb:23:in`countries'

my gemfile 

gem 'spree', github: 'spree/spree', branch: '2-1-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '2-1-stable'
gem 'spree_i18n', github: 'spree/spree_i18n', :branch => "2-1-stable"
gem 'spree_multi_currency', :path => 'vendor/extensions'

**Comment by ping0xFF** [comment]
did you make a currency_RUB entry in your locales file?
